### ISSUE TITLE
License headers!

### ISSUE THREAD

**Issue by eparovyshnaya** [arsysop/liho#2]
Yeah. 
Each `Liho` source file must have a license header! 

In scope of the task 
 - a license(s) must be selected for the product,
 - header text must be invented and approved,
 - all sources. whos format provide commenting functions, must be headed with the agreed header text.

**Comment by eparovyshnaya** [comment]
@ruspl-afed will you approve EPL-2.0 for this ArSysOp product?

**Comment by ruspl-afed** [comment]
> @ruspl-afed will you approve EPL-2.0 for this ArSysOp product?

👍

**Comment by eparovyshnaya** [comment]
@ruspl-afed 
Can we use basic EPL-2.0 header described in [EPH](https://www.eclipse.org/projects/handbook/#ip-copyright-headers)?

/********************************************************************************
 * Copyright (c) 2020 ArSysOp 
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   ArSysOp - initial API and implementation
 ********************************************************************************/

**Comment by eparovyshnaya** [comment]
Closed by pr #6
